<%@ Page Title="" Language="C#" MasterPageFile="~/CicekciSablon.Master" AutoEventWireup="true" CodeBehind="uyelik_sözlesmesi.aspx.cs" Inherits="AspCicekci.uyelik_sözlesmesi" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <p style="box-sizing: border-box; font-weight: normal; margin: 0px 0px 11px; color: rgb(0, 0, 0); font-family: function_probook; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        Üyelik Bilgilendirmeleri ve Sözleşmesi</p>
    <p style="box-sizing: border-box; font-weight: normal; margin: 0px 0px 11px; color: rgb(0, 0, 0); font-family: function_probook; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        Üyelik işlemleriniz tamamlandığında bu Üyelik Bilgilendirmeleri-Sözleşmesi&#39;&#39;ni (form-metin olarak) Üyelik Bilgileri&#39;&#39;nde belirttiğiniz mail adresine göndereceğiz. Ayrıca Sitemizde yine form olarak yer almaktadır. Üyeye &quot;özel&quot; (taraf olarak bilgileri girilmiş) Sözleşme metni gibi bir metin Şirketimiz sistemlerinde ayrıca muhafaza edilmeyebilecektir.</p>
    <p style="box-sizing: border-box; font-weight: normal; margin: 0px 0px 11px; color: rgb(0, 0, 0); font-family: function_probook; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        Dilediğiniz her zaman yukarıda belirtilen iletişim kanallarından Şirketimize yapacağınız sözlü veya yazılı bildirim ile, herhangi bir gerekçe göstermeksizin ve ceza ödemeksizin üyeliğinizi sona erdirebilirsiniz (Sitemiz üyeliğinden ayrılmak için Şirketimiz&#39;&#39;in gönderdiği tüm e-postalarda yer alan “üyelikten ayrıl” linkini de kullanabilirsiniz); aynı şekilde Şirketimiz de üyelikleri sona erdirebilir.</p>
    <p style="box-sizing: border-box; font-weight: normal; margin: 0px 0px 11px; color: rgb(0, 0, 0); font-family: function_probook; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        Şirketimiz ve Sitemizde üye-müşteri bilgilerinin gizliliği, korunması, işlenmesi-kullanımı, ticari elektronik iletişimler ve diğer hususlarda aşağıda cari esasları belirtilen Gizlilik Kuralları-Politikası ve Kullanım Şartları geçerlidir.</p>
    <ul style="box-sizing: border-box; font-weight: normal; margin-top: 0px; margin-bottom: 11px; color: rgb(0, 0, 0); font-family: function_probook; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; list-style-type: disc;">
        <li style="box-sizing: border-box; font-weight: 400 !important;">Üyeler tarafından verilen bilgilerin ve işlemlerin güvenliği için gerekli önlemler bilgi ve işlemin mahiyetine göre Şirketimiz veya ilgili kuruluşça sistemlerde ve internet altyapısında alınmıştır. Sitemizi kullanımlarınızda tüm kredi kartı işlemleri ve onayları Şirketimiz ‘den bağımsız olarak ilgili Banka ve benzeri Kart Kuruluşlarınca online olarak aranızda gerçekleştirilmektedir (Kredi kartı &quot;şifresi&quot; gibi bilgiler Şirketimiz tarafından tarafından görülmez ve/veya kaydedilmez).</li>
        <li style="box-sizing: border-box; font-weight: 400 !important;">Üyelerimize ait bilgiler yasal düzenlemelerin öngördüğü sorumluluklarımız çerçevesinde ilgili kuruluşlara açıklanabilir. Ayrıca, verdikleri kişisel bilgiler ile alışverişlerine dair her türlü kişisel olan-olmayan bilgileri, kanunlara uygun biçimde, Şirketimiz tarafından, her türlü, ürün-hizmet tanıtımı, reklam, iletişim, promosyon, satış, pazarlama, mağaza kartı, kredi kartı ve üyelik bilgilendirmeleri, uygulamaları ve işlemleri yapılması amacı ile süresiz olarak veya yasal/öngörülecek süre için kaydedilebilir, yazılı/manyetik arşivlerde muhafaza edilebilir, kullanılabilir, güncellenebilir, paylaşılabilir, transfer olunabilir ve sair suretler ile işlenebilir.</li>
        <li style="box-sizing: border-box; font-weight: 400 !important;">Üyelerimiz arzu ettikleri her zaman ve hiçbir gerekçe göstermeksizin (yukarıda-aşağıda) belirtilen iletişim kanallarından Şirketimize ulaşarak kişisel veri kullanımı-işlenmelerini ve/veya taraflarına ticari elektronik iletişimleri durdurabilirler. Üyenin bu husustaki açık bildirimine göre, kişisel veri işlemleri ve/veya belirttiği kanallar için tarafına iletişimler yasal azami süre içinde durdurulur (yasalara göre mümkün-gereken işlem ve iletişimler devam eder). Üye dilerse ayrıca, hukuken muhafazası gereken ve/veya mümkün olanlar haricindeki bilgileri, veri kayıt sisteminden silinir ya da kimliği belli olmayacak biçimde anonim hale getirilir. Üye isterse kişisel verilerinin işlenmesi ile ilgili işlemler hakkında Şirketimize her zaman başvurabilir ve bilgi alabilir. Bu hususlardaki başvuru ve talepleri yasal azami süreler içinde yerine getirilecek yahut hukuki gerekçesi tarafına açıklanarak kabul edilmeyebilecektir.</li>
    </ul>
    <p style="box-sizing: border-box; font-weight: normal; margin: 0px 0px 11px; color: rgb(0, 0, 0); font-family: function_probook; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        Tüm bu konularda ek bilgi almak için Şirketimize danışabilirsiniz.</p>
    <p style="box-sizing: border-box; font-weight: normal; margin: 0px 0px 11px; color: rgb(0, 0, 0); font-family: function_probook; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        Üyelerimiz talep ve şikayetlerini şu iletişim kanallarından ulaşarak Şirketimize bildirebilir.</p>
    <p style="box-sizing: border-box; font-weight: normal; margin: 0px 0px 11px; color: rgb(0, 0, 0); font-family: function_probook; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
    <p style="box-sizing: border-box; font-weight: normal; margin: 0px 0px 11px; color: rgb(0, 0, 0); font-family: function_probook; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
</asp:Content>
